jnunemaker/httparty

spec/httparty/hash_conversions_spec.rb

Create a basic spec for HashConversion

Create spec for HashConversion

---

lib/httparty/request.rb
spec/httparty/request_spec.rb

Correct redirect url for redirect paths without leading slash fixes #377

---

lib/httparty/logger/logger.rb
spec/httparty/logger/logger_spec.rb

Enable adding custom loggers to available formatters.

Custom loggers

---

lib/httparty/logger/apache_formatter.rb
lib/httparty/logger/curl_formatter.rb
lib/httparty/logger/logger.rb
spec/httparty/logger/apache_formatter_spec.rb
spec/httparty/logger/curl_formatter_spec.rb
spec/httparty/logger/logger_spec.rb

the loggers are really formatters. Rename as such

Rename the loggers to formatters

---

lib/httparty.rb

add doc to explain `body_steam` param and `stream_body` param

add doc for `body_stream` and 'stream_body'

---

lib/httparty/request.rb
spec/httparty/request_spec.rb
spec/support/stub_response.rb

Always maintain method for 307 & 308 responses

---

lib/httparty/request.rb

Return if gzip response body is nil

---

README.md
docs/README.md

* Adds `docs` directory
* Adds `README.md` file under `docs` with documentation about SSL

Adds docs directory with SSL configuration help

---

lib/httparty/net_digest_auth.rb
spec/httparty/net_digest_auth_spec.rb

This fixes the nil error and enables to read the reponse again.

---

spec/httparty/request_spec.rb

Fix typos in cookie spec descriptions

---

lib/httparty/request.rb
spec/httparty/request_spec.rb

Fixes #404 . This behavior is consistent with cURL:
https://github.com/bagder/curl/blob/6beb0eee/lib/http.c#L710
Another way to demonstrate the new behavior:
```python
import SimpleHTTPServer
class RequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
def do_GET(self):
if self.path == "/":
self.send_response(302)
self.send_header("Location",   "http://127.0.0.1:8000/2")
print self.headers
elif self.path == "/2":
self.send_response(302)
self.send_header("Location",   "http://localhost:8000/3")
print self.headers
else:
self.send_response(200)
print self.headers
if __name__ == '__main__':
SimpleHTTPServer.test(HandlerClass=RequestHandler)
```
Send a request that uses basic auth:
```ruby
HTTParty.get "http://username:password@127.0.0.1:8000"
```
Server responses:
```http
GET / HTTP/1.1 …
```

Don't send basic auth header when redirecting to different hosts

---

Gemfile

More information about what's new in RSpec 3.4 can be found at:
http://rspec.info/blog/2015/11/rspec-3-4-has-been-released/

Upgrade RSpec to 3.4 and Cucumber to 2.3

---

examples/README.md
examples/stream_download.rb

It was a bit hard to understand how to work with stream mode so I've added example for stream mode.

Added example for stream mode

---

lib/httparty/request.rb
spec/httparty/request_spec.rb

Deal with network-path reference redirects

---

lib/httparty/request.rb

Fixes https://github.com/jnunemaker/httparty/issues/552

Fixed assignment warning

---

lib/httparty/hash_conversions.rb

Avoid variable shadowing in hash conversions

---

.editorconfig
examples/README.md
features/steps/mongrel_helper.rb
lib/httparty.rb
lib/httparty/connection_adapter.rb
lib/httparty/hash_conversions.rb
lib/httparty/module_inheritable_attributes.rb
lib/httparty/net_digest_auth.rb
lib/httparty/response.rb
lib/httparty/response/headers.rb
spec/httparty/connection_adapter_spec.rb
spec/httparty/net_digest_auth_spec.rb
spec/httparty/response_spec.rb
website/css/common.css

Noticed some unattended whitespace lying around the codebase. Inferred an editorconfig and applied it wherever I could with minor changes. 
Also added the config file to make things a little easier for future potential contributors.

Adds editorconfig

---

docs/README.md
examples/microsoft_graph.rb

I sort of had to piece together how to do this from the PR that added multipart support.  Thought maybe adding an example would be helpful.

added Multipart Post to Docs.

---

examples/microsoft_graph.rb
lib/httparty/request.rb
lib/httparty/request/body.rb
spec/httparty/request/body_spec.rb
spec/httparty/request_spec.rb

Add ability to force multipart

---

httparty.gemspec
lib/httparty.rb
lib/httparty/request/body.rb
spec/httparty/request/body_spec.rb

Determine content_type for multipart payload

---

lib/httparty/connection_adapter.rb
spec/httparty/request_spec.rb

I came across the typo and just fixed.

Fix typo: HTTPParty -> HTTParty

---

.travis.yml

Ruby versions taken from this page: https://www.ruby-lang.org/en/downloads/releases/

Travis tests: Update Ruby to latest versions

---

lib/httparty/response.rb
spec/httparty/response_spec.rb

Unparseable body exception fix

---

Gemfile
lib/httparty/request.rb
spec/httparty_spec.rb

Fixes https://github.com/jnunemaker/httparty/issues/665

Normalize urls with URI adapter to allow International Domain Names support

---

lib/httparty/response.rb

Regarding https://github.com/jnunemaker/httparty/issues/568

Add response.nil? deprecetion warning

---

lib/httparty/cookie_hash.rb
spec/httparty/cookie_hash_spec.rb

Per https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-02#section-5.3.7

Support SameSite attribute in cookies

---

lib/httparty/request/body.rb
spec/httparty/request/body_spec.rb

Multipart/Form-Data: rewind files after read

---

examples/aaws.rb

It moves the auth param to an instance variable. Also, it fixes how Active
Support core extensions are loaded.
https://guides.rubyonrails.org/active_support_core_extensions.html#cherry-picking-a-definition

Fix Amazon search example

---

docs/README.md

very minor grammar changes in docs

 README.md update

---

docs/README.md
lib/httparty/decompressor.rb
spec/httparty/decompressor_spec.rb

Follows same implementation of how Brotli and LZW are done today.

Support zstd decompression
