- lib/httparty/hash_conversions.rb
1) I think using dangerous ```chop!``` is unnecessary , you can use this:
```ruby
def self.to_params(hash)
params = hash.to_hash.map { |k,v| normalize_param(k,v) }.join
params.chop
end
```
2) Using ```params``` variable is not necessary, using chop in chain is more concise and used in the same way as map, join method
3) Tests are added in previous pr #367
> refactor HTTParty::HashConversions.to_params

- lib/httparty/hash_conversions.rb
- lib/httparty/request.rb
URI.encode is an alias for URI.escape which has been deprecated. There
is a great stackoverflow question discussing this deprecation and
possible replacements, http://stackoverflow.com/a/2832003/1769125. 
After some testing I decided that ERB::Util.url_encode was the best choice as
it most closely mirrored the current implementation.
```ruby
foo = "http://google.com?query=hello"
old_way = URI.escape(foo, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))
#=> "http%3A%2F%2Fgoogle.com%3Fquery%3Dhello"
new_way = ERB::Util.url_encode(foo)
#=> "http%3A%2F%2Fgoogle.com%3Fquery%3Dhello"
old_way == new_way
#=> true
```
> Replace URI.encode with ERB::Util.url_encode

- lib/httparty.rb
Just a quick fix for an issue I was experiencing.  The error I was encountering was from line 34 of `hash_conversions.rb`.
This address [Issue 398](https://github.com/jnunemaker/httparty/issues/398)
Output of `bundle exec rake`:
```
Finished in 1.26 seconds (files took 0.2498 seconds to load)
414 examples, 0 failures
Randomized with seed 49033
Coverage report generated for RSpec to /Users/forrest.fleming/httparty/coverage. 664 / 700 LOC (94.86%) covered.
```
...
```
31 scenarios (31 passed)
155 steps (155 passed)
0m14.276s
```
> Require ERB to prevent errors in HashConversions

- lib/httparty.rb
- lib/httparty/connection_adapter.rb
- lib/httparty/request.rb
- spec/httparty/connection_adapter_spec.rb
- spec/httparty_spec.rb
This option allows you to roll out fancier URI implementations like the one
offered by the Addressable gem.
Addressable is a replacement for the URI implementation that is part of
Ruby's standard library. It more closely conforms to RFC 3986, RFC 3987,
and RFC 6570 (level 4), additionally providing support for IRIs and URI
templates. http://addressable.rubyforge.org/
*Sample Usage:*
```javascript
require 'httparty'
require 'addressable/uri'
require 'pp'
class Foo
include HTTParty
uri_adapter Addressable::URI
end
pp Foo.get('http://svd_identity.spinninpodcasts.com/rss')
```
Fixes #394
> Allow setting a custom URI adapter

- lib/httparty/parser.rb
- spec/httparty/parser_spec.rb
JSON.load is unsafe to use on untrusted user input:
https://www.ruby-lang.org/en/news/2013/02/22/json-dos-cve-2013-0269/
http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html#method-i-load
JSON.parse should be used instead.
This change enables quirks_mode so as to reduce breakages from this
change. Quirks mode enables the parsing of json values other than
objects or arrays, which matches the behaviour of JSON.load.
Note: there still may be breaking changes due to the differences between
load and parse:
- nil and empty string are not parsed by parse, they are parsed as nil
by load
- NaN is not parsed by parse, it is parsed as NaN by load
- parse does not allow nesting of more than 100 to prevent stack level
too deep errors, load has no such limit
> Use JSON.parse instead of JSON.load

- httparty.gemspec
In our local usability testing, we've found the addition of this party popper emoji to considerably improve the efficiency and productivity of our workflow.
> Adds party popper emoji to post install message

- bin/httparty
- features/command_line.feature
Added functionality that allows users to type '--version' at the command line and be presented with the current working version on their machine.
Also added cucumber feature tests to ensure the functionality is working correctly.
> Add version output

- README.md
the code example in the README:
```ruby
response = HTTParty.get('https://api.stackexchange.com/2.2/questions?site=stackoverflow')
```
uses `https://` instead of `http://`.
this makes the following example using `base_uri` appear to default to prefixing the base uri with `https://`.  it's my understanding that the default is `http://`.
```ruby
base_uri 'api.stackexchange.com'
```
the PR updates `https://` to be `http://` in the first example to avoid confusion.
> update code example in README to avoid confusion w base_uri method

- features/digest_authentication.feature
- features/steps/mongrel_helper.rb
- features/steps/remote_service_steps.rb
- lib/httparty/net_digest_auth.rb
- spec/httparty/net_digest_auth_spec.rb
Hi,
I've implemented support for the algorithm=MD5-sess header, as specified in RFC2617.
This addresses bug #200 
New tests added, and all tests pass ( had to change the address used from 0.0.0.0 to 127.0.0.1 locally in all cases, though. Don't know why) 
I've also tested against an IIS8.5 server with digest auth enabled.
Let me know if there's anything else required.
Tony
> Added support for RFC2617 MD5-sess algorithm type

- lib/httparty.rb
- spec/httparty_spec.rb
This attempts to resolve #345. I'm pretty confident the code works, but I couldn't get the spec figured out. I left my attempt in there, with the expectation line commented out. 
Suggestions welcome/encouraged.
> Add default option on head requests

- lib/httparty/request.rb
- spec/support/stub_response.rb
Tested on master:
```
➜  httparty git:(master) cat redirect.rb
require 'sinatra'
post '/redirect-307' do
redirect '/target', 307
end
post '/target' do
'Target'
end
```
```
➜  httparty git:(master) ruby -Ilib -rhttparty -e 'HTTParty.post "http://localhost:4567/redirect-307"'
```
```
➜  httparty git:(master) ruby redirect.rb
Puma 2.11.3 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
== Sinatra/1.4.5 has taken the stage on 4567 for development with backup from Puma
127.0.0.1 - - [16/Sep/2015:14:22:02 -0700] "POST /redirect-307 HTTP/1.1" 307 - 0.0048
127.0.0.1 - - [16/Sep/2015:14:22:02 -0700] "GET /target HTTP/1.1" 404 443 0.0017
^C== Sinatra has ended his set (crowd applauds)
```
`Net:HTTTP` status codes should always be handled …
> Request method is not being preserved on 307 and 308 redirects 

- lib/httparty/parser.rb
- spec/httparty/parser_spec.rb
Use case: some servers have been known to serve files with
Content-Types like “video/mp4; charset=utf-8”, which HTTParty dutifully
tells ruby is a UTF-8 string.  However, before the Parser can decide
that MP4 is not a format it is capable of parsing, the response body is
tested for emptiness … after whitespace is stripped.
Since the String isn’t actually a valid UTF-8 String, this raises an
ArgumentError.  This patch fixes that error by avoiding the call on
Strings that are not validly encoded.
> Avoid calling String#strip on invalid Strings

- httparty.gemspec
Since @jnunemaker will never remove the message (even though he never sees it because he runs with `--quiet`), at least make it so that the regular output is ASCII.
> Remove high-byte emoji from post-install message

- lib/httparty/request.rb
- spec/httparty/request_spec.rb
Some servers (including YouTube) will send a redirect response with a
Content-Encoding header, but no body.  Since inflating an empty body
raises an exception, we should minimally work around this problem for
non-terminal redirect responses.
Note that this will still attempt to inflate a redirected response body
if HTTParty is not configured to follow redirects (which will raise
exceptions if the body is empty), and this does nothing to protect
against otherwise empty responses with a compressed Content-Encoding
(which may indicate a mis-configured server).
> Stop trying to deflate responses that redirect.

- examples/tripit_sign_in.rb
Old example is putting `response.headers['Set-Cookie']` into `request.options[:headers]['Cookie']` directly.
The `Set-Cookie` which responsed from server is looks like
```
Set-Cookie: PHPSESSID=bo2h26ffuqvs91k1dig5g77694; path=/; HttpOnly, _csrf=5182ab96214158ac793b299fc8cc8164689cc0ccfff119152c22817fcb03eccca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22QGX1SwJAwz_9GpUUuETOnTlIUgzf4S_c%22%3B%7D; path=/; httponly
```
But `Cookie` which we will sent to server is looks like
```
Cookie: PHPSESSID=bo2h26ffuqvs91k1dig5g77694; _csrf=5182ab96214158ac793b299fc8cc8164689cc0ccfff119152c22817fcb03eccca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22QGX1SwJAwz_9GpUUuETOnTlIUgzf4S_c%22%3B%7D
```
The value is not equal, and some HTTP servers ( which I have tried Apache ) …
> fix cookie bug in tripit-sign-in example

- features/steps/httparty_response_steps.rb
- features/steps/remote_service_steps.rb
- spec/httparty/cookie_hash_spec.rb
This pull request does two things:
- Fix deprecations that are raised by Aruba. Future versions of Aruba will certainly break a handful of tests.
- Extend a few of the Cucumber steps to be more flexible.
- I have a few other tests I'm writing for extremely long timeouts, which I'm not committing. I don't want to include them and mark them as pending when they're not pending. And they add a huge amount of time to test runs, because they're testing huge amounts of time.
No new features in this pull request, just some cleanup. Everything passes on Ruby 2.2.3.
> Fix deprecations, and add additional steps that we're using.

- features/steps/httparty_response_steps.rb
- lib/httparty/response.rb
- spec/httparty/response_spec.rb
Fixes a step definition that appeared to check response type against a user defined class but actually always checked against String.
Adds support for `is_a?` and `kind_of?` to the `HTTParty::Response` object and uses the fixed step definition to test the implementation.
Previously these were delegated to the `parsed_response` object, which led to unpredictable behaviour; such as:
```ruby
response.class == HTTParty::Response #true
response.is_a?(HTTParty::Response) # false
```
> Implement is_a? and kind_of? in httparty response

- lib/httparty/connection_adapter.rb
- spec/httparty/connection_adapter_spec.rb
####What does this PR do?
* Honors the verify option to prevent `http.verify_mode` when using `pem` or `pk12` options
> Solves #266 - Honors the verify option to avoid overrides

- lib/httparty.rb
- lib/httparty/response.rb
- spec/httparty/response_spec.rb
- spec/httparty_spec.rb
Implements the proposal #454   
When you use httparty in many different projects it starts to become tedious to add a verification on every request. To accomplish this, you have to do something like this: 
```ruby
module Api
class Base
include HTTParty
def get(path, options = {})
raises_unless_success { self.class.get path, options }
end
private
def raises_unless_success
httparty = yield
fail HTTParty::Error, "Code #{httparty.code} - #{httparty.body}" unless
httparty.response.is_a?(Net::HTTPSuccess)
httparty
end
end
end
```
I believe this is not a straight solution.
```ruby
module Api
class Base
include HTTParty
raise_on (400..599).to_a
def get(path, options = {})
self.class.get path, options
end
end
end
```
> Raise on some HTTP status codes

- lib/httparty/connection_adapter.rb
- spec/httparty/connection_adapter_spec.rb
This is useful when a proxy is used by default but you do not want to use it for some requests
> Allow nil http_proxyaddr to pass through to Net::HTTP

- lib/httparty/logger/curl_formatter.rb
- spec/httparty/logger/curl_formatter_spec.rb
This PR changes Logger::CurlFormatter and comprehends this:
1. Adds URI's query parameters to the log output;
1. Adds URI's full address (host + path) to the log output;
1. When you use a query through an option the parameters aren't logged;
1. When base_uri is set, only the path is being logged;
```ruby
class DuckDuckGo
include HTTParty
base_uri 'duckduckgo.com'
logger ::Logger.new("httparty.log"), :debug, :curl
def search(options = {})
self.class.get '/', options
end
end
DuckDuckGo.new.search(query: {q: 'httparty'})
```
```
D, [2016-01-19T17:32:25.802087 #26988] DEBUG -- : [HTTParty] [2016-01-19 17:32:25 -0200] > GET /
[HTTParty] [2016-01-19 17:32:25 -0200] > 
[HTTParty] [2016-01-19 17:32:25 -0200] > 
[HTTParty] [2016-01-19 17:32:25 -0200] < HTTP/1.1 301
[HTTParty] [2016-01-19 17:32:25 …
```
> Logs 'base_uri' and query at Logger::CurlFormatter

- lib/httparty/cookie_hash.rb
- spec/httparty/cookie_hash_spec.rb
Solves https://github.com/jnunemaker/httparty/issues/459. `Hash#reject` returns a new hash instead of mutating. http://ruby-doc.org/core-2.2.0/Hash.html#method-i-reject
> Use reject instead of delete_if to prevent mutation

- httparty.gemspec
JSON support is in Ruby since 1.9 so there is no need to have json gem as a dependency.
Inspired by this Rack’s PR https://github.com/rack/rack/pull/1011
> Remove json gem

- lib/httparty.rb
- lib/httparty/request.rb
- spec/httparty/request_spec.rb
- spec/httparty_spec.rb
`MKCOL` - part of the [HTTP Extensions for Distributed Authoring](http://www.webdav.org/specs/rfc2518.html) (also known as WebDAV) - allow creation of a new collection resource at the location specified.
By extending with the `MKCOL` method, will cover (most) basic WebDAV implementation and make `httparty` more generic and increase the fun :smile:
> Implemented support for MKCOL method

- lib/httparty/request.rb
- spec/httparty/request_spec.rb
Calling `HTTParty::ClassMethods.base_uri` or passing `base_uri` to a request method do not behave the same way. The class method call normalize the uri, while passing options does not. 
This will throw an error due to the url no being valid (it lacks the scheme in the url)
```ruby
HTTParty.get('/resource', {
base_uri: 'foo.com',
body: {}
})
```
But this will works fine,[`HTTParty.normalize_base_uri`](https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L107) takes care of adding the scheme  
```ruby
class Myclass
include HTTParty
base_uri 'foo.com'
def get_it
get('/resource', {
body: {}
})
end
end
```
> Fix base uri options not normalized

- lib/httparty.rb
This behavior appears to have changed with 49956a707e31a231a6670027222a213280d65d22, but the documentation was not updated at that time. Apologies in advance if I've misunderstood something.
> Update post method documentation examples

- lib/httparty/hash_conversions.rb
- spec/httparty/hash_conversions_spec.rb
- spec/httparty/request_spec.rb
Fixes #469 
Now we have:
```
>> res = HTTParty.get('http://github.com', query: {fake_array: []})
>> res.request.last_uri.to_s
=> "https://github.com/?fake_array[]="
```
And:
```
>> res = HTTParty.get('http://github.com', query: {fake_array: [1]})
>> res.request.last_uri.to_s
=> "https://github.com/?fake_array[]=1"
```
Besides this fix I'd like to know what happens if you have something like this: `HTTParty::Request.new(Net::HTTP::Get, 'http://google.com', query: { fake_array: [""] })`
> Allow empty array to be used as a params in get requests.

- lib/httparty/exceptions.rb
- lib/httparty/request.rb
- spec/httparty/exception_spec.rb
- spec/httparty/request_spec.rb
This handles duplicate location headers for #478
> Handle duplicate location headers

- lib/httparty/response.rb
- spec/httparty/response_spec.rb
Expands the existing `respond_to?` first-party method list to include the HTTP status predicates. Useful for things like RSpec, which check `respond_to?` when using predicate matchers - beyond that it makes for a more consistent and predictable object (If I can call it, it should `respond_to?`).
Because `Response` inherits from `BasicObject` we miss out on quite a few of these pre-made tools from `Object`, though it looked like moving away from `BasicObject` was a bigger task and would require a bit more debate. I figured this was the simplest change to make.
I have not checked for other methods that could be added to `RESPOND_TO_METHODS`, my concern was with the predicate methods.
> Add status predicate methods to Response#respond_to?

- lib/httparty.rb
- lib/httparty/hash_conversions.rb
- lib/httparty/request.rb
HTTParty users that only require parts of it, e.g. `HashConversions` via `require 'httparty/hash_conversions'`, will see `uninitialized constant HTTParty::HashConversions::ERB` if their code does not itself `require 'erb'`. this is because ERB is only properly required when HTTParty is required with `require 'httparty'`. this PR allows users to use the parts of HTTParty that require ERB without having to `require 'erb'` in their code.
> Require ERB where it's used

- History.md
History not having an extension breaks changelog parsers like [vandamme](https://github.com/tech-angels/vandamme)
> Convert History file to markdown

- README.md
Clicking on `Docs` link in the README file is currently giving a 404.
> Fixing Docs link in README file

- README.md
- examples/aaws.rb
- examples/crack.rb
- examples/custom_parsers.rb
- examples/delicious.rb
- examples/stackexchange.rb
- examples/tripit_sign_in.rb
- examples/twitter.rb
- examples/whoismyrep.rb
Did this because the nested hashes with inconsistent styles was driving me mad. 
Also willing to create the reverse version as PR if deemed better, eg. always having no space between hash opening and closing brackets:
`{herp: derp}`
Just, please, one style 😄
> add spacing to example hashes

- History.md
Help people upgrade to 0.14.0 by clarifying that there are no breaking changes.
Other tips you might like: http://keepachangelog.com/en/0.3.0/
> Docs: Classify changes in 0.14.0

- README.md
- docs/README.md
How to symbolize JSON keys or suppress parsing?
https://github.com/jnunemaker/httparty/issues/500
> Update README with parsing JSON keys as symbols

- lib/httparty/connection_adapter.rb
- lib/httparty/net_digest_auth.rb
- lib/httparty/request.rb
- lib/httparty/response.rb
- lib/httparty/response/headers.rb
- spec/httparty/net_digest_auth_spec.rb
- spec/httparty/request_spec.rb
- spec/httparty/response_spec.rb
Hi, I have been working with this library for about a week now and have found some problems
1. `HTTParty::Request#handle_deflation` does not do anything useful. In actuality, decompression is performed by `Net::HTTP.` The `Net::HTTP::GenericRequest` object has a 'decode_content' value (boolean) that the documentation says is false if 'Accept-Encoding' is specified. This is done with a check in the '[]=' operator on the class, but this isn't called. HTTParty uses the 'initialize_http_header' method, which does not perform this check. So decode_content is always true. When the `Net::HTTP::Response` object is instantiated, this is copied over. Then `Net::HTTP` performs the decompression. Not only is 'handle_deflation' dead code, there is already an implementation of this in Net::HTTP …
> Fix numerous bugs, design issues, and documentation

- lib/httparty/parser.rb
- spec/httparty/parser_spec.rb
- spec/httparty/request_spec.rb
Closes #498 
Currently, HTTParty errors when you try to parse JSON that has a utf-8 BOM. Since .NET applications automatically prepend the BOM characters, this severely limits the usefulness of HTTParty when talking to Windows-based JSON services.
This PR resolves that issue by stripping the BOM characters before parsing the JSON response.
> [#498] Handle utf-8 bom for json parsing

- lib/httparty.rb
- spec/httparty_spec.rb
Previously, calling `HTTParty.headers` without an argument set
`HTTParty.default_options[:headers]` to an empty hash. Now the
default headers will only be set to an empty hash when one is
explicitly provided, otherwise they will remain `nil`.
The previous behavior was problematic because the default headers
for a request could either be `nil` or `{}`, depending on whether
`HTTParty.headers` had been called. When they are `nil` the
default headers from Net::HTTP are used.
@jnunemaker any feedback is appreciated! This feels to me like a bit more of a workaround than a real solution, but I don't see a cleaner solution without a somewhat larger refactor.
Thanks to @tomatoturnip for the original [PR](https://github.com/jnunemaker/httparty/pull/508).
> Do not overwrite default headers unless specified

- lib/httparty/request.rb
- spec/httparty/request_spec.rb
JSON API generally handles query string list parameters by comma-separating the values:
```
/articles?include=author&fields[articles]=title,body,author&fields[people]=name 
(with encoded '[' and ']' characters)
```
The default serializer and the `NON_RAILS_QUERY_STRING_NORMALIZER` currently creates duplicate query params with each value in a list:
```
Default
/articles?include=author&fields[articles][]=title&fields[articles][]=body&fields[articles][]=author&fields[people]=name 
NON_RAILS
/articles?include=author&fields[articles]=title&fields[articles]=body&fields[articles]=author&fields[people]=name 
```
This PR adds another query string normalizer that will produce URLs of the first format, which will work out of the box with JSON API-compliant APIs.
> Add JSON_API_QUERY_STRING_NORMALIZER

- lib/httparty/response/headers.rb
The delegate library is not auto-required in Ruby 2.2.x, so we need to explicitly require it if we are using SimpleDelegator.
> Add missing require to headers.rb

- lib/httparty/request.rb
- spec/httparty/request_spec.rb
In c46663d73ff96d86b92d36208a021bbe58672e7c a change was made to clean up the `encode_with_ruby_encoding` method. 
Previously, the `force_encoding` method was always called and then there was a `rescue` that would just return the `body`. If a request had a `nil` body, the `rescue` made sure that a `nil` value (the original `body`) would be returned.
After c46663d73ff96d86b92d36208a021bbe58672e7c, if a response had a `nil` body, an error would be thrown when parsing the response.
This PR includes a spec that reproduces the error and a fix that adds a `nil` check to make sure we do not call `force_encoding` on `nil`. If the `body` is `nil`, we will return `nil`. This matches the previous behavior.
> Handle an HTTP Response with a Content-type but no body.

- lib/httparty/parser.rb
- spec/httparty/parser_spec.rb
Closes #533 
Fixes an issue where ASCII-8BIT encodings blow up with a `gsub` call to strip the UTF8 BOM.
> [#533] Prevent gsub errors with different encodings

- lib/httparty/request.rb
A response with an empty body would cause `force_encoding` to be called on nil. Also removed a few trailing whitespaces.
> Prevent passing nil to encode_body.

- lib/httparty/parser.rb
- spec/httparty/parser_spec.rb
Closes #539
Apparently I like breaking stuff with my changes 😭 . This PR fixes `gsub!` from breaking on frozen string literals.
Some of the tests around this were actually stubbing the `body` call directly, instead of setting the data. I've changed these tests to inject the data instead. As a high-level note, a lot of tests for `Parser` are stubbing private methods, which I don't think is a good way to structure tests.
We should be able to test all use cases of `Parser` through the external API. When we stub, or test directly, internal methods, any implementation change can break any number of other tests, even if the change doesn't affect external behavior.
> [#539] Use non-destructive gsub, fix test stubbing

- lib/httparty/request.rb
- spec/httparty/request_spec.rb
Somewhere along the line, it looks like responses stopped getting the encoding specified by the `Content-Type` header applied unless the header’s value was an exact, case-sensitive match for an encoding’s name in Ruby.
In a lot of real-world scenarios, encodings will be referenced in lower-case (internally, they are all upper-case in Ruby) or by other well-known aliases, e.g. `eucKR` is an alias for `EUC-KR` and `CP65001` is an alias for `UTF-8`.
This also updates tests—they were previously passing erroneously and didn’t *actually* test the behavior they were meant to. Test values were already correct and didn’t need the behavior the tests were looking for to be applied.
This fixes #542 and possibly #541.
> Ensure correct encoding is used for Content-Types that are lower-case or aliases

- .travis.yml
- Gemfile
- spec/httparty/request_spec.rb
- spec/httparty/ssl_spec.rb
- spec/httparty_spec.rb
- spec/spec_helper.rb
Fakeweb hasn't had a release in years and sadly no longer appears to be maintained. As a result tests are failing on more modern Rubies (2.4.x). This change replaces Fakeweb with Webmock, which is actively maintained, making tests green on all supported Rubies.
Fixes https://github.com/jnunemaker/httparty/issues/510 and https://github.com/jnunemaker/httparty/issues/524
> Replaces Fakeweb with Webmock in tests.

- docs/README.md
This might be a long shot (and a very minor one too), but while I was checking out some examples in [docs/README](https://github.com/jnunemaker/httparty/blob/master/docs/README.md), I noticed that most of them are not properly indented.
- The official [README.md](https://github.com/jnunemaker/httparty/blob/master/README.md) uses 2 spaces. This PR is just following the consistency for the docs.
- Might be opinionated, but 2-spaces is already considered as a [community standard](https://github.com/bbatsov/ruby-style-guide#spaces-indentation).
- This will reduce the cognitive load when reading the code
- When copying the code snippets to our favorite editors (probably for those who haven't discovered auto indent), it requires another action for the developer to trim the spaces just to make …
> Give some spacing love to code snippets in docs/README

- lib/httparty/exceptions.rb
When I raise a HTTParty::ResponseError, the log message is not very helpful.
```rb
raise HTTParty::ResponseError.new(response)
```
```
HTTParty::ResponseError: { "status"=>"error", "message"=>"That's not how this works, that's not how any of this works!" }
```
```
HTTParty::ResponseError: HTTParty::ResponseError
```
So I added the response to the error message.
> Add ResponseError response attribute to message

- lib/httparty/parser.rb
- spec/httparty/request_spec.rb
JSONAPI is using this content-type `application/vnd.api+json`, so just added it to the parsing list.
> add ability to parse response from JSONAPI

- lib/httparty/cookie_hash.rb
- spec/httparty/response_spec.rb
Ruby 2.4 caused the specs to become slightly noisier due to a deprecation warning for `Fixnum` and a warning in Ruby's `reject` (see https://github.com/ruby/ruby/blob/v2_4_1/hash.c#L1335-L1337 ). This PR makes a couple of small tweaks to eliminate the new warnings.
> Silence some noisy spec warnings in Ruby 2.4

- lib/httparty/response.rb
As discussed in #567, the changes introduced 5a78a14 resulted in change of
behavior when viewing the Response objects using command line version of the
HTTParty or tools like pry.
This changs adds minimal version of the #pretty_print method that behaves the
same as code before, when response was inheriting from BasicObject rather than
Object. This is because PP::ObjectMixin applies to Object, but it not
BasicObject.
Following this commit, both CLI version of httparty and pry work correctly (as they did initially).
> add Response#pretty_print | Restore documented behavior

- lib/httparty/parser.rb
- spec/httparty/request_spec.rb
This change allows the parsing of content with `application/hal+json` content-type (which is just JSON anyway) as JSON when using the `#parsed_response` method.
Currently this content type is ignored and the method returns a String. Since HAL is just JSON with an additional specification for how some metadata should be included it can be parsed as regular JSON.
More on HAL here: http://stateless.co/hal_specification.html
An example of it in the wild in the Stellar Horizon API: https://horizon.stellar.org/
> Parse content with application/hal+json content type as JSON

- lib/httparty/request/body.rb
- spec/httparty/request/body_spec.rb
I am using a gem ([ocr_space](https://github.com/suyesh/ocr_space)) that [passes a boolean param](https://github.com/suyesh/ocr_space/blob/master/lib/ocr_space/convert.rb#L17) to `HTTParty.post`. This started failing in v0.16 with the following error message:
```ruby
TypeError: no implicit conversion of false into String
from /gems/httparty-0.16.0/lib/httparty/request/body.rb:40:in `+'
```
> Fix multipart uploads with boolean params.

- lib/httparty/request.rb
- spec/httparty/request_spec.rb
`@raw_request.initialize_http_header` resets the headers, so when options contained :headers, it always erased the Content-Type header set for multipart.
Now the Content-Type header is always set to "multipart/form-data" when body is detected as multipart. This is IMHO not correct, but that's how the original implementation was designed…
Related to: #569
Notify: @TheSmartnik
> Fix multipart to set its header even when other headers are provided

- spec/httparty/connection_adapter_spec.rb
- spec/httparty/net_digest_auth_spec.rb
- spec/httparty/parser_spec.rb
- spec/httparty/request_spec.rb
- spec/httparty/response_spec.rb
- spec/httparty_spec.rb
This change cleans up some of the warnings output when running test suite.
- Removes the redefining of `MyParser` class in individual tests.
- Instantiates all variables that are used while tests are running with sensible defaults (they're actually fine to be `nil`, so long as they're defined).
- Removes a specific error check that could create false positives.
An error with the SSLTestServer support object related to unknown CAs isn't fixed by this.
> Fix rspec warnings

- lib/httparty/hash_conversions.rb
- spec/httparty/hash_conversions_spec.rb
Had the same problem as was mentioned in Issue #574. 
The normalize_param expected an array structure of
``` [ [key_a, value_a], [key_b, value_b] ]```
However when recursing you would get structure like this, 
```[ [key_a, value_a, key_b, value_b] ]```
> Correctly handle nested params

- Changelog.md
- lib/httparty/request/body.rb
Using the `path` method instead of passing the file directly to `File.basename` ensures that `ActionDispatch::Http::UploadedFile` can be used again.
Related issue: https://github.com/jnunemaker/httparty/issues/584
Note: ActionDispatch isn't a dependency of the library, so I opted not to write a test specifically for it. I tried to account for it in the existing tests by checking that e.g. `to_str` isn't called on the file object, but that didn't work since `File.basename` is implemented in C.
> Support ActionDispatch::Http::UploadedFile again

- httparty.gemspec
this PR points the gemspec homepage at a page that exists - or if the page just got lost somewhere, restoring it would resolve this issue.
> gemspec homepage does not exist

- lib/httparty/logger/apache_formatter.rb
- lib/httparty/logger/curl_formatter.rb
- spec/httparty/logger/apache_formatter_spec.rb
This PR introduces following changes:
1. Use `public_send` instead of `send` for calling logger's public method.
2. Unify naming of a method returing formatted `Time.now` (`current_time` vs `time`).
3. Adjust `ApacheFormatter` to be more similar to `CurlFormatter` (private methods instead of multiple local variables, log message extracted to a dedicated method).
> Unify loggers

- lib/httparty/logger/logger.rb
- lib/httparty/logger/logstash_formatter.rb
- spec/httparty/logger/logger_spec.rb
- spec/httparty/logger/logstash_formatter_spec.rb
ELK Stack (Elasticsearch, Logstash & Kibana trio) is commonly used today for collecting and presenting logs.
Logstash, to parse logs correctly, needs to have them delivered in a compatible JSON format:
```
{
"message"    => "hello world",
"@version"   => "1",
"@timestamp" => "2018-10-09T23:03:14.111Z",
"type"       => "stdin",
"host"       => "hello.local"
}
```
Only `@timestamp` & `@version` are required.
* `@timestamp` is the ISO8601 high-precision timestamp for the event.
* `@version` is the version number of this json schema
Every other field is valid and fine.
To support Logstash format by default I introduced a brand new `LogstashFormatter`. It generates a compatible JSON message with the following fields:
```
{
"@timestamp" => "2018-10-09 17:54:58 +0200",
"@version" => 1, …
```
> Add Logstash-compatible formatter

- examples/README.md
- examples/body_stream.rb
- examples/multipart.rb
- lib/httparty.rb
Adds examples of `multipart` and `body_stream` options
> Add more examples

- lib/httparty/response.rb
- spec/httparty/response_spec.rb
Fixes #143
@jnunemaker Hi, would love to hear your feedback on this one. It looks fine, but I could've forget something
> Fix response object marshalling

- lib/httparty.rb
- lib/httparty/utils.rb
- spec/httparty_spec.rb
FIxes https://github.com/jnunemaker/httparty/issues/472
> Stringify headers

- Changelog.md
- lib/httparty/version.rb
@jnunemaker can you please release a new version?
I want to start working on https://github.com/jnunemaker/httparty/issues/494 and maybe on https://github.com/jnunemaker/httparty/issues/511. Both of these will require minor version update as they may introduce slight backward incompatibility
> Bump version to 0.16.3

- spec/fixtures/ssl/generate.sh
See #604 
Not sure if I should run the file and commit the new certs in spec/fixtures/ssl/generated/
Tests pass both with the old certs and new ones if I generate them again
> Replace c_rehash with openssl rehash - Fixes #604

- .travis.yml
- lib/httparty/response.rb
- spec/httparty/response_spec.rb
On ruby/ruby@660740a75dd9526ad9a2732ea87c8ab5a385ef1f , some status codes have been updated.
Add aliases so old names can still be used with ruby >= 2.6.
Added aliases are:
- `gateway_time_out?` → `gateway_timeout?`
- `request_entity_too_large?` → `payload_too_large?`
- `request_time_out?` → `request_timeout?`
- `request_uri_too_long?` → `uri_too_long?`
- `requested_range_not_satisfiable?` → `range_not_satisfiable?`
It solves issues you will have with ruby 2.6.0 like
~~~
irb(main):001:0> http_response.request_time_out?
NoMethodError: undefined method `request_time_out?' for #<HTTParty::Response:0x0000563c88932270>
Did you mean?  request_timeout?
from …/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/httparty-0.16.2/lib/httparty/response.rb:101:in `method_missing'
~~~
> Add Ruby 2.6 compatibility and tests

- lib/httparty/connection_adapter.rb
- spec/spec_helper.rb
This was causing me trouble for a while until I figured it out. Interestingly, it's the same issue that's been addressed in [Faraday](https://github.com/lostisland/faraday/pull/793/files#diff-d8775963a7e225c40196fd205b28a626R127) a while ago that I ran into as well and resolved with an upgrade.
The problem is that when doing HTTPS requests the cert store is reinitialized over and over again and we're seeing huge memory leaks in our application over time.
> Cache default certs store to prevent memory leaks

- examples/stream_download.rb
- lib/httparty/fragment_with_response.rb
- lib/httparty/request.rb
- spec/httparty/fragment_with_response_spec.rb
- spec/httparty_spec.rb
Add a `:stream_body_include_response_code` option to get a response code back with the fragment when streaming data. This allows for skipping redirects while streaming (and other error detection), which before would tack the redirect onto the file.
We needed this, I appreciate any suggestions.
> stream_body fragment include http_response feature

- lib/httparty/request/body.rb
- spec/httparty/request/body_spec.rb
This PR intends to fix a few issues with the `multipart?` method:
1. It wasn't working for params that respond to `#to_hash` but not to `#detect` (like `ActionDispatch::Request::Session`). Same for params that respond to `#to_ary` but not to `#detect`
```ruby
class HashLike; def to_hash; { a: 3 }; end; end
HTTParty::Request::Body.new(a: HashLike.new).multipart? # NoMethodError: undefined method `detect' for #<HashLike:0x00007fbf8971ae08>
```
2. Wasn't detecting files inside arrays
(`includes_hash?(value)` was always returning `true` for not empty arrays, because all objects respond to `#hash`, and then it was doing `hash.detect do |key, value| ` with an array which actually yields only one arg)
```ruby
HTTParty::Request::Body.new(a: [Tempfile.new(['some_temp_file','.gif'])]).multipart? # …
```
> HTTParty::Request::Body#multipart? fixes

- Gemfile
- lib/httparty.rb
- lib/httparty/request.rb
- lib/httparty/text_encoder.rb
- spec/httparty/request_spec.rb
- spec/httparty_spec.rb
- spec/spec_helper.rb
- spec/support/stub_response.rb
> [WIP] Fix encoding of streamed chunk

- lib/httparty/text_encoder.rb
Calling the `force_encoding` method on frozen strings can be a problem.
Especially for people using the `# frozen_string_literal: true` annotation.
To protect it, I added a call to `dup` before all calls to `force_encoding`.
If we decide the bump the ruby version to something newer we could use the `+`.
Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>
> Avoid modifying frozen strings

- examples/README.md
- examples/peer_cert.rb
- lib/httparty/fragment_with_response.rb
- lib/httparty/request.rb
- spec/httparty/fragment_with_response_spec.rb
- spec/httparty/ssl_spec.rb
- spec/support/ssl_test_helper.rb
This provides access to the connection object,
which in turn exposes properties like `.peer_cert`
for performing additional validation against
x509 certificates.
Closes #633, Follow-up to #634
> Expose .connection on fragment block param

- .travis.yml
- lib/httparty.rb
- lib/httparty/connection_adapter.rb
- spec/httparty/connection_adapter_spec.rb
- spec/httparty_spec.rb
[The method](https://ruby-doc.org/stdlib-2.6/libdoc/net/http/rdoc/Net/HTTP.html#method-i-write_timeout-3D) was introduced in Ruby 2.6.0.
The gem already supports `open_timeout` & `read_timeout` options, so it would be nice to provide support for `write_timeout` as well.
From the official documentation:
> Number of seconds to wait for one block to be written (via one write(2) call). Any number may be used, including Floats for fractional seconds. If the HTTP object cannot write data in this many seconds, it raises a Net::WriteTimeout exception. The default value is 60 seconds. Net::WriteTimeout is not raised on Windows.
> Add support for `Net::HTTP#write_timeout` method (Ruby 2.6.0)

- httparty.gemspec
`#test_files`seem to be redundant https://github.com/rubygems/rubygems/issues/735
By removing test files from the gem, it becomes two times lighter _(From 90.5KiB to 42.5KiB)_
> Remove test_files from gemspec

- lib/httparty/connection_adapter.rb
- spec/httparty/connection_adapter_spec.rb
`Net::HTTP` had this weird behaviour of retry once on timeout for `GET` & `PUT` requests. On Ruby 2.5.0 `Net::HTTP` introduced retry configuration option https://github.com/ruby/ruby/pull/1654
Found out that `HTTParty` doesn't support it yet. I added `max_retries` option pass to `Net::HTTP` from `ConnectionAdapter`
> Add max_retries support

- lib/httparty.rb
- lib/httparty/headers_processor.rb
- spec/httparty/headers_processor_spec.rb
- spec/httparty_spec.rb
I encountered the following problem: API required checksum based on the request body.
This simple change allows using request options in block header like in this example:
```ruby
headers 'X-SIGNATURE' => lambda { |options|
Digest::SHA256.hexdigest(options[:body] + configuration.api_secret)
}
```
> Pass options to dynamic block headers

- Changelog.md
Just a small update to point to https://github.com/jnunemaker/httparty/pull/660 for `max_retries` information - looks like an incorrect one got copy/pasted in the changelog.
> Point to correct PR URL for `max_retries`

- lib/httparty/cookie_hash.rb
- spec/httparty/cookie_hash_spec.rb
Akamai, whether due to a bug or intentional change, started to send HTTP responses with Set-Cookie headers that appear to violate the Cookie RFC by including a blank parameter. Traditional browsers appear to handle the change without issue, but HTTParty throws an exception when copying this cookie from the response to a subsequent request.
Sample invalid header:
```
Set-Cookie: somekey=someval; domain=mydomain.com; path=/; ; Secure
```
This change silently drops the invalid parameter and treats the remainder of the header as valid.
> Support edge case cookie format with a blank attribute

- lib/httparty.rb
There is some attributes that don't follow the rdoc attributes format. 
Example:
https://rdoc.info/github/jnunemaker/httparty/HTTParty/ClassMethods
> Update some attributes rdoc format

- features/handles_compressed_responses.feature
- features/steps/httparty_response_steps.rb
- features/steps/httparty_steps.rb
- features/steps/mongrel_helper.rb
- lib/httparty/request.rb
httparty relies on Net::HTTP's built in transparent support for gzip and deflate
transfer encoding, however that did not work if you specified your own explicit headers
because calling Net::HTTPHeader#initialize_http_header overwrites the work done in
Net::HTTPGenericRequest#initialize to set the default User-Agent, Accept,
and Accept-Encoding.  This also removes the need to duplicate the logic in
Net::HTTP around not decoding the response if the caller has explicitly set
the Accept-Encoding for their own purposes.
This does introduce a slight incompatible change in behavior where
previously specifying any custom headers would omit the default headers,
while with the new behavior you can override the values however
can't omit them entirely.
While I'm here, also remove the test for HEAD …
> Support gzip/deflate transfer encoding when explicit headers are set.

- lib/httparty/cookie_hash.rb
Just a small thing I saw when looking at the gem diff.
Renamed "value" to "data" so we don't have two things named "value" in the same context.
Possibly "k" and "v" would be better since it's more consistent with `to_cookie_string`.
> cookie_hash.rb cleanup

- docs/README.md
Key `pem_password` is missing.
> Fixed SSL doc example.

- lib/httparty/hash_conversions.rb
- spec/httparty/hash_conversions_spec.rb
- spec/httparty/request/body_spec.rb
- spec/httparty/request_spec.rb
As noted in #687, the existing implementation of our querystring
construction was not valid according to the HTTP/1.1 specification,
which was noticed with an integration issue with Apache Tomcat.
This affects both the generation of Query Strings, and URL encoded form
parameters.
The solution is to ensure that we always URL-encode the keys, as well as
the values.
It appears that the existing test we had for this, "returns a Rails
style query string", was not actually quite testing what we thought it
was, as we had not tested the rendering of the raw values, only the URL
decoded ones.
Closes #697.
> Fix: URL Encode keys and values in URL encoded form data

- .rubocop_todo.yml
Received an error while doing on a project that has httparty dependency.
```bash
rubocop --safe-auto-correct
```
```
Error: The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/httparty-0.18.0/.rubocop_todo.yml, please update it)
```
> Rename cop Lint/HandleExceptions to Lint/SuppressedException

- lib/httparty/exceptions.rb
The title says it all - just fixing a minor typo I noticed while reading through the source code.
> Fix typo in exceptions.rb docs

- spec/httparty/request/body_spec.rb
Ruby 3.0.0 requires transforming a hash to named parameters for method calls. This fix gets all tests to pass for Ruby 3.0.0 as well as older versions of Ruby (I tested 2.6.3).
> Fix method call in spec for Ruby 3.0.0

- docs/README.md
- lib/httparty.rb
- lib/httparty/decompressor.rb
- lib/httparty/parser.rb
- lib/httparty/request.rb
- spec/httparty/decompressor_spec.rb
- spec/httparty/request_spec.rb
- spec/httparty/ssl_spec.rb
- spec/httparty_spec.rb
Better handling of `Accept-Encoding` / `Content-Encoding` decompression:
1. By default, let `Net::HTTP` always do decompression, if it can.
2. Add support to decompress `"br"` ([Brotli](https://en.wikipedia.org/wiki/Brotli)) and `"compress"` (LZW) if the required gems are present. These are not supported by `Net::HTTP`
3. Add `:skip_decompression` option to disable both Net::HTTP and HTTParty decompression (i.e. 1 and 2 above)
4. Add "HTTP Compression" section to docs/README.md
This fixes #562 and reverts some `Accept-Encoding` behavior in v0.18.x back to how it was in v0.17.3 and prior.
PR #678, released in v0.18.0, introduced undesirable behavior which broke my app in production.
* In v0.17.3 and prior, you could set the `Accept-Encoding` header (e.g. `gzip`, etc.) in a request, and …
> Better handling of Accept-Encoding / Content-Encoding decompression (fixes #562)

- .github/workflows/ci.yml
This PR leverages the bundler-cache feature of the Ruby-maintained Action setup-ruby.
[See ruby/setup-ruby](https://github.com/ruby/setup-ruby/blob/master/action.yml) for more information.
> CI: use ruby/setup-ruby + bundler-cache

- Changelog.md
- README.md
- httparty.gemspec
> Require ruby >= 2.3

- lib/httparty/connection_adapter.rb
- spec/httparty/connection_adapter_spec.rb
I just threw this together but it seems to work, specs pass. Use case is connecting to Kubernetes 1.19 cluster which uses an EC key. Original code's call to `OpenSSL::PKey::RSA.new` on the key raises `OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error`
`OpenSSL::PKey::EC.new` works for the EC key, but from the docs it appears `OpenSSL::PKey.read` is an agnostic solution that will auto-return the right PKey type so should work for RSA/DSA/EC?
> switch :pem option to to OpenSSL::PKey.read to support other algorithms

- .github/workflows/ci.yml
This is a very small change, add Ruby 3.0 to build matrix.
...but which avoids a Float-to-String loss of characters.
An example (not from this project) of what it can look like before this change, in this picture:
Read more details, if you like: https://github.com/actions/runner/issues/849
> CI: Add "3.0" to build matrix

- .github/workflows/ci.yml
- .simplecov
- spec/spec_helper.rb
This PR adds Ruby 3.1 to the CI matrix.  It includes two other changes:
1. Removes the .simplecov file, which causes an error on Ruby 3.1 (coverage attempts to start twice)
2. Removes the require "pry", as pry is not going to be the Ruby debugger going forward
> Adds Ruby 3.1 to CI

- README.md
The #670 pull request has a few asks for improvements. This addresses
all of those improvements and makes some additional grammatical and
formatting adjustments in spirit of the PR feedback.
The `ActiveSupport::to_params` has been substituted for
`HTTParty::HashConversinos.to_params` since the PR comment hinted at
that, and a quick search pulled that up. Maybe it's inaccurate though -
feel free to correct.
> backtick code symbols, fix grammar/spelling

- lib/httparty/text_encoder.rb
`dup` was introduced [here](https://github.com/jnunemaker/httparty/commit/d90a62f8da6f5f9c01dba1644dd1591a2f6ebc81) to avoid problems where response body was frozen. Unfortunately, it came with a huge memory penalty and caused a memory leak
Following https://gitlab.com/gitlab-org/gitlab/-/issues/29196 and using [provided benchmark](https://gitlab.com/brodock/benchmark-http-clients) here are the results (GC was disabled)
Before
```
rake download
HTTParty: 221.54 MB
```
After
```
rake download
HTTParty: 15.67 MB
```
---
Memory leak during upload was fixed with https://github.com/jnunemaker/httparty/pull/711
> Do not dup nonfrozen string on download (Fix memory leak)

- lib/httparty.rb
net/https is no longer needed since Ruby 2, according to the docs.
https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html#class-Net::HTTP-label-HTTPS
> Remove redundant require

- docs/README.md
Addresses https://github.com/jnunemaker/httparty/issues/743
This change adds docs regarding how to send data in JSON format. Users are often<sup>[1][2]</sup> on how to format JSON data to use in POST, PUT and PATCH requests. This adds simple examples on how to do so.
1: https://stackoverflow.com/questions/7455744/post-json-to-api-using-rails-and-httparty
2: https://github.com/jnunemaker/httparty/issues/743
> Add docs on JSON post, put and patch requests

- Gemfile
- Guardfile
- lib/httparty/request.rb
- spec/httparty/request_spec.rb
Marshalling should really make the object as exactly the same as possible. I really need to just do all ivars that are not procs but this fixes the problem for now and I don't think it breaks anything for others.
fyi @baberthal who added request marshalling
xref #764
> Request marshal fix

- Changelog.md
- httparty.gemspec
- lib/httparty.rb
- lib/httparty/request/body.rb
`mini_mime` is a minimal mime type library that's more performant and less memory hungry.
https://github.com/discourse/mini_mime
It has replaced `mime-types` in the `mail` gem: (which is a dependency of `actionmailer`, and by extension, `rails`)
https://github.com/mikel/mail/pull/1059
As well as `capybara`:
https://github.com/teamcapybara/capybara/pull/1884
Which also means using it as a dependency of `httparty` would be able to reuse the same dependency that should be already available in most Rails apps, instead of pulling in an extra `mime-types` dependency.
The change in code is pretty straightforward, the same one made by the capybara PR linked above.
> Suggestion: Replace `mime-types` with `mini_mime` for content type lookup

- lib/httparty.rb
- spec/httparty_spec.rb
I'm writing a small extension for HTTParty to add [AWS Signature V4](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) on HTTParty requests. This is achieved by adding computed headers to an existing request object based on its attributes like HTTP method, URL and body. Currently request object is not exposed, so, I end up building a request object and then signing it:
```ruby
class Client
def self.foo(body)
sign_v4(Net::HTTP::Post, "/foo", {body:}).perform
end
def self.sign_v4(http_method, path, options = {})
options = ModuleInheritableAttributes.hash_deep_dup(default_options).merge(options)
HeadersProcessor.new(headers, options).call
process_cookies(options)
request = Request.new(http_method, path, options)
signature = …
```
> Extract request building method

- httparty.gemspec
In Ruby 3.4, the `csv` gem will not be a default gem. Since httparty uses CSV directly, we should add it as a gem dependency.
```
/usr/local/bundle/ruby/3.3.0/gems/httparty-0.21.0/lib/httparty.rb:10: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of httparty-0.21.0 to add csv into its gemspec.
```
> Add CSV gem as a dependency for Ruby 3.4

- lib/httparty/request.rb
- spec/httparty/request_spec.rb
Problem: Ran into a web application firewall that was blocking requests because the originating POST body was retained and transmitted upon redirection. 
Solution: When redirecting, clear the body if the subsequent request is a GET
Note: Also extracted a method to keep the handle_response method more concise and cohesive IMHO
> Clear body when redirecting to a GET 

- lib/httparty/module_inheritable_attributes.rb
This makes it hard to track down code when profiling etc.
> Avoid anonymous eval

- features/steps/mongrel_helper.rb
- lib/httparty.rb
- lib/httparty/logger/logstash_formatter.rb
- lib/httparty/parser.rb
- lib/httparty/request/body.rb
- spec/httparty/logger/logstash_formatter_spec.rb
- spec/httparty/parser_spec.rb
Only load them when they are used.
> Lazy load some gems

- lib/httparty/request.rb
- spec/httparty/request_spec.rb
Currently, we can create a valid httparty request with a `base_uri` and a relative path. However, there is an issue where by the request will not be redirected with the http authentication credentials if the request is created this way.
This PR fixes that issue by validating if the host of the `uri` is the same as the host of the `redirect_path`
With the following `Request`:
> Redirect with authorization credentials to same host for relative paths

- httparty.gemspec
This adds the changelog_uri to the gemspec metadata,
pointing to the GitHub releases page.
> Add changelog_uri metadata to gemspec

- lib/httparty/request/body.rb
- spec/httparty/request/body_spec.rb
Fixes #821 
```
irb(main):003> HTTParty.post('http://localhost:8888', body: { user: { name: "John Doe", avatar: File.open(path) } })
=> #<HTTParty::Response:0xb070 parsed_response=nil, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-length" => ["0"]}>
irb(main):004> HTTParty.post('http://localhost:8888', body: { user: { name: "John Doe", avatar: File.open(path, 'rb') } })
=> #<HTTParty::Response:0xf0f0 parsed_response=nil, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-length" => ["0"]}>
irb(main):005> HTTParty.post('http://localhost:8888', body: { user: { name: "Jöhñ Ďœ", avator: File.open(path) } })
=> #<HTTParty::Response:0x10ca0 parsed_response=nil, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-length" => ["0"]}>
irb(main):006> …
```
> Fix multipart with files in binary mode and fields including non-ASCII characters
